Make User registration in firebase
GameofSource-GFG/Android-Development pull request #54
Opened 2020-10-25 17:38 UTC by singhtaran1005

GOSA16
ISSUE #45 

#### Describe the changes you've made
I have connected UI registration with Firebase and google sign in with Firebase as mentioned in the issue.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
Add any other context or screenshots about the feature request here.

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GameofSource-GFG/Web-Development/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

2020-10-25 19:22 UTC, VarunSAthreya requested changes
There are 3 changes:
1. Change the position of the push statement.
2. Add signup routename
3. Install `fluttertoast` package. (Merge conflicts will be fixed later)

2020-10-25 19:22 UTC, VarunSAthreya commented on lib/screens/sign_up.dart
> +                            Navigator.push(
Remove push function here

2020-10-25 19:22 UTC, VarunSAthreya commented on lib/screens/sign_up.dart
> +        .then((result) {})
And then add it here in `.then()` function

2020-10-25 19:22 UTC, VarunSAthreya commented on lib/screens/sign_up.dart
> -  static final String routeName = "/sign_up";
Add this again

2020-10-26 03:04 UTC, singhtaran1005 commented
changes done

2020-10-26 12:51 UTC, VarunSAthreya approved these changes
Congratulations on the successful merge!
The next set of issues would be out soon.

2020-10-26 12:52 UTC, merged